# Generated by Django 6.0.5 on 2026-07-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFQProcesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq', models.CharField(max_length=50, verbose_name='RFQ')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('fecha_arranque', models.DateField(blank=True, null=True, verbose_name='Fecha de arranque')),
                ('solicitante', models.CharField(blank=True, max_length=200, verbose_name='Solicitante')),
                ('planta', models.CharField(blank=True, max_length=200, verbose_name='Planta')),
                ('archivo_nombre', models.CharField(blank=True, max_length=255, verbose_name='Archivo origen')),
                ('estado', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], default='ok', max_length=10)),
                ('accion', models.CharField(blank=True, max_length=20, verbose_name='Accion')),
                ('campos_faltantes', models.CharField(blank=True, max_length=255)),
                ('mensaje', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RFQ procesado',
                'verbose_name_plural': 'RFQ procesados',
                'ordering': ['-creado_en'],
            },
        ),
    ]
