# Generated by Django 6.0.5 on 2026-07-07 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfqprocesado',
            options={'ordering': ['-creado_en'], 'permissions': [('puede_confirmar', 'Puede confirmar escritura al Excel')], 'verbose_name': 'RFQ procesado', 'verbose_name_plural': 'RFQ procesados'},
        ),
        migrations.AddField(
            model_name='rfqprocesado',
            name='campos_editados',
            field=models.CharField(blank=True, max_length=255, verbose_name='Campos editados manualmente'),
        ),
        migrations.AddField(
            model_name='rfqprocesado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs_procesados', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
    ]
